background           #101418
foreground            #e0e2e8
selection_foreground  #99ccfa
selection_background  #003352
cursor                #99ccfa
cursor_text_color     #101418
cursor_trail          1
background_opacity    0.6